#!/bin/bash
API_URL="https://pokeapi.co/api/v2/pokemon/"

OUTPUT_FILE="data.json"
ERROR_FILE="errors.txt"

response = $(curl -s -w "%{http_code}" "$API_URL")

http_code = ${response:-3}
response_body = ${response%???}
if ["$http_code" -eq 200];then
echo "$response_body"> "$OUTPUT_FILE"
echo "Successfully saved Pickachu data to $OUTPUT_FILE"
else 
 error_message ="Erroe:Request failed with HTTP status code $http_code"
 if [-n "$response_body"]; then
   error_message+="\nResponse body: $response_body"
 fi
 echo -e "$error_message" > "$ERROR_FILE"
 echo "Error: Failed to fetch data. Check $ERROR_FILE for details."
 exit 1
fi