#!/bin/bash

INPUT_FILE="data.json"
if [! -f "$INPUT_FILE" ]; then
    echo "Input file '$INPUT_FILE' does not exist."
    exit 1
fi
name=$(jq -r '.name' "$INPUT_FILE")
height=$(jq -r '.height' "$INPUT_FILE")
weight=$(jq -r '.weight' "$INPUT_FILE")
type=$(jq -r '.types[0].type.name' "$INPUT_FILE")

height_m=$(echo "height / 10"|bc -l)
weight_kg=$(echo "weight / 10"|bc -l)

echo "Name: $name"